### ISSUE TITLE
CMAKE ERROR

### ISSUE THREAD

**Issue by econsysqtcam** [monkey/duda#36]
Hi,

    I am trying to compile duda webservice framework i am getting the following error.  How to solve this?

CMake Error at CMakeLists.txt:34 (MONKEY_PLUGIN):
Unknown CMake command "MONKEY_PLUGIN".

Thanks,

With Regards,
Vishnu Kumar T S

**Comment by edsiper** [comment]
Hi @econsysqtcam , the GIT Master of Duda is not yet aligned to the latest changes from Monkey core base, so that branch is totally under development and should not be used yet for development. 

The __dst-1__ GIT branch is the one you want to use to build your own web services, it's the stable version. We can chat more about it in our Slack channel if you want: http://slack.monkey-project.com
